version: '3.8'

services:
  master_ds:
    container_name: master_ds
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - .:/code
    networks:
        - master_ds

  dbs_postgre:
    profiles: ["hw_dbs"]
    container_name: master_ds_dbs_postgre
    image: postgres
    restart: always
    volumes:
      - ./data/dbs_postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    networks:
      - master_ds

  dbs_mongodb:
    profiles: ["hw_dbs_mongo"]
    image: mongo
    container_name: master_ds_dbs_mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=main
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongodb/entry:/docker-entrypoint-initdb.d
      - ./mongodb:/data/db
      - ./mongodb/mongoconfig:/data/configdb
    networks:
      - master_ds

networks:
  master_ds:
    driver: bridge